#!/bin/sh
preselection='pt_1>50&&pt_2>40&&'\
'abs(eta_1)<2.1&&abs(eta_2)<2.1&&newCHIso18_1<2.5&&newCHIso18_2<2.5' 

preselectionMTD='pt_1>50&&pt_2>40&&'\
'abs(eta_1)<2.1&&abs(eta_2)<2.1&&newCHIso3_1<2.5&&newCHIso3_2<2.5' 

preselectionVBF='pt_1>50&&pt_2>40&&'\
'mjj>400&&njets>=2&&(abs(jdeta)>2.5)&&'\
'abs(eta_1)<2.1&&abs(eta_2)<2.1&&newCHIso18_1<2.5&&newCHIso18_2<2.5' 

preselectionVBFMTD='pt_1>50&&pt_2>40&&'\
'mjj>400&&njets>=2&&(abs(jdeta)>2.5)&&'\
'abs(eta_1)<2.1&&abs(eta_2)<2.1&&newCHIso3_1<2.5&&newCHIso3_2<2.5' 

preselectionBoosted='pt_1>50&&pt_2>40&&'\
'higgsPt>200&&'\
'abs(eta_1)<2.1&&abs(eta_2)<2.1&&newCHIso18_1<2.5&&newCHIso18_2<2.5' 

preselectionBoostedMTD='pt_1>50&&pt_2>40&&'\
'higgsPt>200&&'\
'abs(eta_1)<2.1&&abs(eta_2)<2.1&&newCHIso3_1<2.5&&newCHIso3_2<2.5' 

#&&'\ #'isoTight_1>0.5&&isoTight_2>0.5&&'\
#'againstMuonTight3_1>0&&againstMuonTight3_2>0&&'\
#'againstElectronVLooseMVA6_1>0&&againstElectronVLooseMVA6_2>0&&'\
#'npv>0&&diLeptons==0&&tightMuons==0&&tightElectrons==0&&extraelec_veto==0&&extramuon_veto==0'
bselection='nbtag>=1'
antibselection='nbtag==0'
wselection='mt_1>70'
signalselection='mt_1<40'
qcdselection=$inclselection
trigselection='pt_1>24' #only for MC
topSF=0.1
trigselectiondata='(HLT_IsoMu22_v_fired>0||HLT_IsoTkMu22_v_fired>0)' #only for Data
relaxedSelection='pt_2>20&&npv>0&&diLeptons==0&&iso_04>0.15&&iso_04<0.3&&tauIsoLoose>0.5'

luminosity=100000 #pb

direc='/scratch/ojalvo/Htt_Sep14_200PU/'
datadirec=$direc
zttScale=0.01.
topWeight=1.0
zWeight=1.0
qcdfactor=100.0
topSF=1.
bins=30
#DYJets.root  ggH125.root  QCD.root  ttBar.root vbfH125.root
binning='binningLowStat=20.,30.,40.,45.,50.,55.,60.,65.,70.,75.,80.,85.,90.,95.,100.,110.,120.,130.,150. binningHighStat=0.,20.,40.,60.,80.,100.,120.,140.,160.,180.,200.,250.,300.,350.' 
mkdir diTauPlots

#m_vis Madgraph
MakeDataCardUpgrade channel='diTau' dataFile='none.root' qcdFile=$direc'QCD.root' zttFile=$direc'DYJets.root' zllFile=$direc'DYJets.root' wFile=$direc'WJETS.root' vvFile=$direc'DiBoson.root' topFile=$direc'ttBar.root' preselection=$preselection  wselection=$signalelection relaxedSelection=$signalSelection  signalselection=$signalselection   luminosityErr=0.045 qcdfactor=1 qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075  topSF=$topSF 	muID=1.00 muIDErr=0.01 eleID=0.0 eleIDErr=0.0 tauID=1.0 tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17    bitmask=1,0,0,0 TTweight='1' Zweight='1' weight='__WEIGHT__'  luminosity=$luminosity  variable='m_vis' bins=20 min=0 max=200 outputFile='diTauPlots/diTau_m_vis.root'  

MakeDataCardUpgrade channel='diTau' dataFile='none.root' qcdFile=$direc'QCD.root' zttFile=$direc'DYJets.root' zllFile=$direc'DYJets.root' wFile=$direc'WJETS.root' vvFile=$direc'DiBoson.root' topFile=$direc'ttBar.root' preselection=$preselectionMTD  wselection=$signalelection relaxedSelection=$signalSelection  signalselection=$signalselection   luminosityErr=0.045 qcdfactor=1 qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075 topSF=$topSF 	muID=1.00 muIDErr=0.01 eleID=0.0 eleIDErr=0.0 tauID=1.0 tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17    bitmask=1,0,0,0 TTweight='1' Zweight='1' weight='__WEIGHT__'  luminosity=$luminosity  variable='m_vis' bins=20 min=0 max=200 outputFile='diTauPlots/diTau_m_vis_mtd.root'  

MakeDataCardUpgrade channel='diTau' dataFile='none.root' qcdFile=$direc'QCD.root' zttFile=$direc'DYJets.root' zllFile=$direc'DYJets.root' wFile=$direc'WJETS.root' vvFile=$direc'DiBoson.root' topFile=$direc'ttBar.root' preselection=$preselectionVBF  wselection=$signalelection relaxedSelection=$signalSelection  signalselection=$signalselection   luminosityErr=0.045 qcdfactor=1 qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075 topSF=$topSF 	muID=1.00 muIDErr=0.01 eleID=0.0 eleIDErr=0.0 tauID=1.0 tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17    bitmask=1,0,0,0 TTweight='1' Zweight='1' weight='__WEIGHT__'  luminosity=$luminosity  variable='m_vis' bins=20 min=0 max=200 outputFile='diTauPlots/diTau_m_vis_vbf.root'  
MakeDataCardUpgrade channel='diTau' dataFile='none.root' qcdFile=$direc'QCD.root' zttFile=$direc'DYJets.root' zllFile=$direc'DYJets.root' wFile=$direc'WJETS.root' vvFile=$direc'DiBoson.root' topFile=$direc'ttBar.root' preselection=$preselectionVBFMTD  wselection=$signalelection relaxedSelection=$signalSelection  signalselection=$signalselection   luminosityErr=0.045 qcdfactor=1 qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075 topSF=$topSF 	muID=1.00 muIDErr=0.01 eleID=0.0 eleIDErr=0.0 tauID=1.0 tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17    bitmask=1,0,0,0 TTweight='1' Zweight='1' weight='__WEIGHT__'  luminosity=$luminosity  variable='m_vis' bins=20 min=0 max=200 outputFile='diTauPlots/diTau_m_vis_vbf_mtd.root'  

MakeDataCardUpgrade channel='diTau' dataFile='none.root' qcdFile=$direc'QCD.root' zttFile=$direc'DYJets.root' zllFile=$direc'DYJets.root' wFile=$direc'WJETS.root' vvFile=$direc'DiBoson.root' topFile=$direc'ttBar.root' preselection=$preselectionBoosted  wselection=$signalelection relaxedSelection=$signalSelection  signalselection=$signalselection   luminosityErr=0.045 qcdfactor=1 qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075 topSF=$topSF 	muID=1.00 muIDErr=0.01 eleID=0.0 eleIDErr=0.0 tauID=1.0 tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17    bitmask=1,0,0,0 TTweight='1' Zweight='1' weight='__WEIGHT__'  luminosity=$luminosity  variable='m_vis' bins=20 min=0 max=200 outputFile='diTauPlots/diTau_m_vis_boosted.root'  
MakeDataCardUpgrade channel='diTau' dataFile='none.root' qcdFile=$direc'QCD.root' zttFile=$direc'DYJets.root' zllFile=$direc'DYJets.root' wFile=$direc'WJETS.root' vvFile=$direc'DiBoson.root' topFile=$direc'ttBar.root' preselection=$preselectionBoostedMTD  wselection=$signalelection relaxedSelection=$signalSelection  signalselection=$signalselection   luminosityErr=0.045 qcdfactor=1 qcdfactorErr=0.02 vvErr=0.3   zttScale=$zttScale zttScaleErr=0.033    wFactorErr=0.06    zjfterr=0.1  zlfterr=0.24   topErr=0.075 topSF=$topSF 	muID=1.00 muIDErr=0.01 eleID=0.0 eleIDErr=0.0 tauID=1.0 tauIDErr=0.06  dir=$direc''  bID=1.0  bIDErr=0.10  bMisID=1.0  bMisIDErr=0.17    bitmask=1,0,0,0 TTweight='1' Zweight='1' weight='__WEIGHT__'  luminosity=$luminosity  variable='m_vis' bins=20 min=0 max=200 outputFile='diTauPlots/diTau_m_vis_boosted_mtd.root'  

